#!/usr/bin/env python3
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#
# Generate rust/crates/unicode/src/tables.rs from
# lib/Platform/Unicode/UnicodeData.inc. The tables are the ID/letter/space range
# tables the JS lexer needs. Re-run when the Unicode data is updated:
#   python3 rust/crates/unicode/gen_tables.py
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
INC = ROOT / "lib/Platform/Unicode/UnicodeData.inc"
OUT = Path(__file__).resolve().parent / "src/tables.rs"

# table name -> expected range count (anti-drift guard)
EXPECTED = {
    "UNICODE_LETTERS": 378,
    "UNICODE_COMBINING_MARK": 266,
    "UNICODE_DIGIT": 69,
    "UNICODE_CONNECTOR_PUNCTUATION": 6,
    "UNICODE_OTHER_ID_START": 4,
    "UNICODE_OTHER_ID_CONTINUE": 7,
    "UNICODE_PATTERN_LETTER": 1,
    "UNICODE_PATTERN_CONTINUE": 0,
}

PAIR = re.compile(r"\{\s*(0x[0-9a-fA-F]+|\d+)\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\}")

def extract(src, name):
    # Try the C-array form, then the std::array form.
    m = re.search(r"UnicodeRange\s+" + name + r"\s*\[\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        m = re.search(
            r"std::array<\s*UnicodeRange\s*,\s*\d+\s*>\s+" + name + r"\s*=\s*\{\{(.*?)\}\};",
            src, re.S)
    if not m:
        sys.exit(f"error: table {name} not found in {INC}")
    pairs = [(int(a, 0), int(b, 0)) for a, b in PAIR.findall(m.group(1))]
    return pairs

def main():
    if not INC.exists():
        sys.exit(f"error: {INC} not found — run from a full hermes checkout")
    src = INC.read_text()
    # Pull the Unicode version line from the .inc header for provenance.
    ver = re.search(r"for Unicode version ([0-9.]+)", src)
    version = ver.group(1) if ver else "unknown"
    out = []
    out.append("// Copyright (c) Meta Platforms, Inc. and affiliates.")
    out.append("//")
    out.append("// This source code is licensed under the MIT license found in the")
    out.append("// LICENSE file in the root directory of this source tree.")
    out.append("//")
    out.append(f"// GENERATED by gen_tables.py from lib/Platform/Unicode/UnicodeData.inc")
    out.append(f"// Unicode version {version}. DO NOT EDIT BY HAND.")
    out.append("//")
    out.append("// Each entry is an inclusive [first, last] code-point range; tables are")
    out.append("// sorted ascending and non-overlapping (required for binary search).")
    out.append("")
    for name, expected in EXPECTED.items():
        pairs = extract(src, name)
        if len(pairs) != expected:
            sys.exit(f"error: {name} has {len(pairs)} ranges, expected {expected}")
        # Sanity: sorted and non-overlapping.
        for i in range(1, len(pairs)):
            if pairs[i][0] <= pairs[i - 1][1]:
                sys.exit(f"error: {name} not sorted/non-overlapping at index {i}")
        out.append(f"pub static {name}: [(u32, u32); {len(pairs)}] = [")
        for a, b in pairs:
            out.append(f"    (0x{a:04x}, 0x{b:04x}),")
        out.append("];")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} (Unicode {version})")

if __name__ == "__main__":
    main()
