[package]
name = "hermes-support"
version = "0.1.1"
edition = "2021"
description = "Diagnostics and source-management support crate for the Hermes Rust front-end."
license = "MIT"
repository = "https://github.com/tmikov/hermes"
authors = ["Tzvetan Mikov <tmikov@gmail.com>"]
categories = ["development-tools"]
readme = "README.md"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
hermes_unicode = { path = "../unicode", version = "0.1.0", package = "hermes-unicode" }
